<a href="https://colab.research.google.com/github/yhy0519/Machine_learning_of_Python/blob/main/python_m04_02_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **■ 로지스틱 회귀(Logistic Regression)**

종속변수가 범주형인 경우에 적용되는 회귀분석 모형 (수제비: p3-8)
(반응변수)

** 회귀분석 종류

    1. 단순 회귀 분석  -->  종속변수가 연속형 수치 데이터
    2. 다항 회귀 분석  -->  종속변수가 연속형 수치 데이터
    3. 다중 회귀 분석  -->  종속변수가 연속형 수치 데이터
    4. 로지스틱 회귀 분석  -->  종속변수가 범주형인 데이터


** 데이터 분석

    1. 이 데이터에 맞는 가장 좋은 머신러닝 알고리즘과 코드는 무엇인지 ?
    2. 이 데이터에 맞는 가장 좋은 파생변수는 무엇인지 ?


**■ 머신러닝 데이터 분석을 하기 위한 단계?**

    1. 데이터 불러오기
    2. 데이터 탐색 및 전처리   --->   결측치 처리
    3. 범주형 변수 더미변수(인코딩)로 변환 (파이썬)
    4. 데이터 정규화 또는 표준화  --->  이상치에 민감하지 않도록 단위를 일정하게 조정
    5. 훈련 데이터와 테스트 데이터 분할
    6. 머신러닝 모델 생성
    7. 훈련 데이터로 머신러닝 모델 훈련
    8. 머신러닝 모델 평가
    9. 머신러닝 모델 성능 개선



**■ 결측치 처리**

머신러닝 데이터 분석의 정확도는 분석 데이터의 품질에 의해 좌우된다.  
데이터 품질을 높이기 위해서는 누락 데이터 처리, 중복 데이터 처리 등
오류를 수정하고 분석 목적에 맞게 변형하는 과정이 필요한다.  
데이터 프레임에는 원소 데이터 값이 종종 누락되는 경우가 있다.  
일반적으로 데이터 값이 존재하지 않는 누락 데이터를 NaN 으로 표시한다.  
머신러닝 분석 모형에 데이터를 입력하기 전에 반드시 누락 데이터를 제거하거나
다른 적절한 값으로 대체하는 과정이 필요하다.  
누락 데이터가 많아지면 데이터의 품질이 떨어지고 머신러닝 분석 알고리즘을
왜곡하는 현상이 발생하기 때문이다.  
그래서 반드시 아래의 3가지 함수를 잘 알고 있어야 한다.

    1. 누락 데이터를 찾는 함수
	   1.1 insull()  : 누락 데이터면 True 를 반환하고, 누락 데이터가 아니면 False 를 반환
	   1.2 notnull() : 누락 데이터가 아니면 True 를 반환하고, 누락 데이터이면 False 를 반환
	
예: 

In [15]:
import seaborn as sns

tat = sns.load_dataset('titanic')
print(tat.head().isnull())
print('\n')
print(tat.head().isnull().sum())

   survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0     False   False  False  False  False  False  False     False  False   
1     False   False  False  False  False  False  False     False  False   
2     False   False  False  False  False  False  False     False  False   
3     False   False  False  False  False  False  False     False  False   
4     False   False  False  False  False  False  False     False  False   

     who  adult_male   deck  embark_town  alive  alone  
0  False       False   True        False  False  False  
1  False       False  False        False  False  False  
2  False       False   True        False  False  False  
3  False       False  False        False  False  False  
4  False       False   True        False  False  False  


survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           3
e

문제29. emp 데이터 프레임의 누락 데이터는 몇개인가?

In [16]:
import pandas as pd

emp = pd.read_csv("/content/drive/MyDrive/data/emp.csv")
print(emp.isnull().sum())

empno        0
ename        0
job          0
mgr          1
hiredate     0
sal          0
comm        11
deptno       0
dtype: int64


    2. 누락 데이터를 제거하는 함수
      2.1 열을 삭제한다.

In [17]:
import seaborn as sns
tat = sns.load_dataset('titanic')
print(tat.isnull().sum())
print('\n')
print(tat.columns)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')


In [18]:
tat.dropna( axis = 1, thresh = 500, inplace = True )
print(tat.columns)  # deck 열 삭제
#설명: 누락데이터(NaN) 이 500개 이상이면 열을 삭제한다.
# inplace = True 를 사용하면 원본(tat) 에서 삭제한다.

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')


In [19]:
# 아래와 같이 tat2 를 만들 때 inplace=True 를 안쓰고 만들면 ?
tat = sns.load_dataset('titanic')
tat2 = tat.dropna(axis=1, thresh=500)
print(tat2.columns)
print('\n')
print(tat.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')


설명: 위와 같이 tat2 를 만들 때  inplace = True 를 안쓰고 만들면 tat2 에는 deck 이 	없어진 상태로 만들어지고 tat 에는 deck이 남아있다. 그러나 inplace = True 를 쓰고 하게 되면 tat2 에도 deck 이 없고 원본이 tat 에도 deck 이 없는 상태가 됩니다.  
	axis = 1 은 축(열)을 날리겠다는 뜻입니다.  
	axis = 0 은 행을 날리겠다는 뜻입니다.


      2.2 행을 삭제한다.

In [20]:
import seaborn as sns
tat = sns.load_dataset('titanic')
print(tat.deck.isnull().sum())  # 688
print(len(tat))  # 891

688
891


In [21]:
tat.dropna(subset=['deck'], axis = 0, inplace=True)
print(tat.deck.isnull().sum())

0


문제30. emp 데이터 프레임에서 comm 의 결측치를 확인하고 comm 의 결측치 행들을 삭제하시오!

In [22]:
print(emp.comm.isnull().sum())   # 11

emp.dropna(axis=0, inplace=True)
print(emp)  # 4개의 행만 남았습니다.

11
   empno   ename       job     mgr    hiredate   sal    comm  deptno
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500     0.0      30


    3. 누락 데이터를 다른 데이터로 치환하는 함수
      3.1 평균값으로 누락 데이터를 바꾸기

In [23]:
import seaborn as sns
tat = sns.load_dataset('titanic')
tat.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [24]:
mean_age = tat['age'].mean(axis=0)
print(mean_age)

29.69911764705882


In [25]:
tat['age'].fillna(mean_age, inplace=True)
tat.tail()

survived  pclass     sex        age  sibsp  parch   fare embarked  \
886         0       2    male  27.000000      0      0  13.00        S   
887         1       1  female  19.000000      0      0  30.00        S   
888         0       3  female  29.699118      1      2  23.45        S   
889         1       1    male  26.000000      0      0  30.00        C   
890         0       3    male  32.000000      0      0   7.75        Q   

      class    who  adult_male deck  embark_town alive  alone  
886  Second    man        True  NaN  Southampton    no   True  
887   First  woman       False    B  Southampton   yes   True  
888   Third  woman       False  NaN  Southampton    no  False  
889   First    man        True    C    Cherbourg   yes   True  
890   Third    man        True  NaN   Queenstown    no   True

문제31. 위의 예제 코드에 나이 데이터를 평균값으로 치환했을때와 안했을때의 차이를 확인하시오 !

In [26]:
import seaborn as sns
tat = sns.load_dataset('titanic')
mean_age = tat['age'].mean()
print(tat.age.isnull().sum())  

177


In [27]:
tat['age'].fillna(mean_age, inplace=True)
print(tat.age.isnull().sum()) 

0


      3.2 최빈값으로 누락 데이터를 바꾸기

In [28]:
import seaborn as sns
tat = sns.load_dataset('titanic')
most_age = tat['age'].value_counts(dropna=True)  # dropna=True : null 값 제외
print(most_age)

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: age, Length: 88, dtype: int64


문제32. 위의 코드에서 최빈값에 해당하는 나이를 출력하고 누락치를 최빈값으로 치환하시오 !

In [29]:
import seaborn as sns
tat = sns.load_dataset('titanic')
most_age = tat['age'].value_counts(dropna=True).idxmax()  # dropna=True : null 값 제외
print(most_age)  
print(tat.age.isnull().sum())  

24.0
177


In [30]:
tat['age'].fillna(most_age, inplace=True)
print(tat.age.isnull().sum()) 

0


      3.3 이웃하고 있는 주변의 데이터로 누락 데이터를 바꾸기

In [31]:
import seaborn as sns
tat = sns.load_dataset('titanic')
tat.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [32]:
tat['deck'].fillna(method='bfill', inplace=True)  # 결측치 아래의 데이터로 채워넣는다.
tat['deck'].fillna(method='ffill', inplace=True)  # 결측치 위의 데이터로 채워넣는다.
tat.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True    C  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False    C  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True    E  Southampton    no   True

      3.4 누락 데이터가 아닌 데이터에 대한 회귀 예측값으로 누락 데이터를 바꾸기

    결측치가 너무 많으면 컬럼을 지운다.
    결측치를 다른값으로 치환하고자 한다면 아래의 4가지 방법으로 치환
    평균값, 최빈값, 주변의 행들로 치환, 회귀분석의 예측값

문제33. emp 데이터 프레임에서 월급과 커미션 컬럼을 삭제하시오

In [33]:
import pandas as pd

emp = pd.read_csv('/content/drive/MyDrive/data/emp.csv')
emp.drop(['sal', 'comm'], axis=1, inplace=True)
emp

empno   ename        job     mgr    hiredate  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22      30
3    7566   JONES    MANAGER  7839.0  1981-04-02      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09      10
7    7788   SCOTT    ANALYST  7566.0  1987-04-19      20
8    7839    KING  PRESIDENT     NaN  1981-11-17      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08      30
10   7876   ADAMS      CLERK  7788.0  1987-05-23      20
11   7900   JAMES      CLERK  7698.0  1981-12-03      30
12   7902    FORD    ANALYST  7566.0  1981-12-03      20
13   7934  MILLER      CLERK  7782.0  1982-01-23      10
14   9292    JACK      CLERK  7782.0  1982-01-23      70

**▦ dropna 의 how 의 의미 ?**

    'any' : If any NA values are aprsent, drop that row or column.
    'all' : If all values are NA, drop that row or column.

예:  

    emp.dropna(axis=0, how='all', inplace=True)  
위의 코드 뜻은 emp 데이터 프레임에서 모든 행이 NA 인 행을 삭제하겠다.  
그런데 emp 데이터 프레임에는 모든 행이 NA 인 컬럼은 없으므로 실행이 되지 않았다.  
그래서 실행해도 14개의 행이 그대로 있는 것이다.

    emp.dropna(axis=0, how='any', inplace=Treu)  
NA 가 있는 행은 무조건 지운다는 뜻입니다.

문제34. emp 데이터 프레임에서 NA 가 있는 행은 무조건 지우시오 ~

In [34]:
import pandas as pd
emp = pd.read_csv('/content/drive/MyDrive/data/emp.csv')
print(len(emp))  # 15
emp.dropna(axis=0, how='any', inplace=True)
print(len(emp))  # 4

15
4


**■ 타이타닉 로지스틱 회귀**


In [35]:
### 기본 라이브러리 불러오기
import pandas as pd
import seaborn as sns

'''
[Step 1] 데이터 준비/ 기본 설정
'''

# load_dataset 함수를 사용하여 데이터프레임으로 변환
df = sns.load_dataset('titanic')

# IPython 디스플레이 설정 - 출력할 열의 개수 한도 늘리기
pd.set_option('display.max_columns', 15)
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [36]:
# 데이터셋 설명(kaggle의 데이터셋 기준)

# - PassengerId : 승객 번호
# - Survived : 생존여부(1: 생존, 0 : 사망)
# - Pclass : 승선권 클래스(1 : 1st, 2 : 2nd ,3 : 3rd)
# - Name : 승객 이름
# - Sex : 승객 성별
# - Age : 승객 나이 
# - SibSp : 동반한 형제자매, 배우자 수
# - Patch : 동반한 부모, 자식 수
# - Ticket : 티켓의 고유 넘버
# - Fare 티켓의 요금
# - Cabin : 객실 번호
# - Embarked : 승선한 항구명(C : Cherbourg, Q : Queenstown, S : Southampton)

In [37]:
# 결측치 확인
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [38]:
# 데이터 자료형 확인
df.info()

# object    <----  문자형
# category  <----  R 의 factor(문자형+level) 와 같음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [39]:
'''
[Step 2] 데이터 탐색/ 전처리
'''

# NaN값이 많은 deck 열을 삭제, embarked와 내용이 겹치는 embark_town 열을 삭제
rdf = df.drop(['deck', 'embark_town'], axis=1)  

# age 열에 나이 데이터가 없는 모든 행을 삭제 - age 열(891개 중 177개의 NaN 값)
rdf = rdf.dropna(subset=['age'], how='any', axis=0)  

# embarked 열의 NaN값을 승선도시 중에서 가장 많이 출현한 값으로 치환하기
most_freq = rdf['embarked'].value_counts(dropna=True).idxmax()   

rdf['embarked'].fillna(most_freq, inplace=True)

rdf.isnull().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [40]:
'''
[Step 3] 분석에 사용할 속성을 선택
'''

# 분석에 활용할 열(속성)을 선택 
ndf = rdf[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked']]
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [41]:
# 원핫인코딩 - 범주형 데이터를 모형이 인식할 수 있도록 숫자형으로 변환
onehot_sex = pd.get_dummies(ndf['sex'])
ndf = pd.concat([ndf, onehot_sex], axis=1)

onehot_embarked = pd.get_dummies(ndf['embarked'], prefix='town')
ndf = pd.concat([ndf, onehot_embarked], axis=1)

# sex, embarked 열 삭제
ndf.drop(['sex', 'embarked'], axis=1, inplace=True)

ndf.head()

survived  pclass   age  sibsp  parch  female  male  town_C  town_Q  town_S
0         0       3  22.0      1      0       0     1       0       0       1
1         1       1  38.0      1      0       1     0       1       0       0
2         1       3  26.0      0      0       1     0       0       0       1
3         1       1  35.0      1      0       1     0       0       0       1
4         0       3  35.0      0      0       0     1       0       0       1

In [42]:
'''
[Step 4] 데이터셋 구분 - 훈련용(train data)/ 검증용(test data)
'''

# 속성(변수) 선택
X=ndf[['pclass', 'age', 'sibsp', 'parch', 'female', 'male', 
       'town_C', 'town_Q', 'town_S']]  #독립 변수 X
y=ndf['survived']                      #종속 변수 Y

X.head()

pclass   age  sibsp  parch  female  male  town_C  town_Q  town_S
0       3  22.0      1      0       0     1       0       0       1
1       1  38.0      1      0       1     0       1       0       0
2       3  26.0      0      0       1     0       0       0       1
3       1  35.0      1      0       1     0       0       0       1
4       3  35.0      0      0       0     1       0       0       1

In [43]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [44]:
# 설명 변수 데이터를 표준화(normalization)
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X

array([[ 0.91123237, -0.53037664,  0.52457013, ..., -0.47180795,
        -0.20203051,  0.53307848],
       [-1.47636364,  0.57183099,  0.52457013, ...,  2.11950647,
        -0.20203051, -1.87589641],
       [ 0.91123237, -0.25482473, -0.55170307, ..., -0.47180795,
        -0.20203051,  0.53307848],
       ...,
       [-1.47636364, -0.73704057, -0.55170307, ..., -0.47180795,
        -0.20203051,  0.53307848],
       [-1.47636364, -0.25482473, -0.55170307, ...,  2.11950647,
        -0.20203051, -1.87589641],
       [ 0.91123237,  0.15850313, -0.55170307, ..., -0.47180795,
         4.94974747, -1.87589641]])

In [45]:
# train data 와 test data로 구분(7:3 비율)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10) 

print('train data 개수: ', X_train.shape)
print('test data 개수: ', X_test.shape)
print('\n')

train data 개수:  (499, 9)
test data 개수:  (215, 9)




In [46]:
'''
[Step 5] 로지스틱 분류 모형 - sklearn 사용
'''

# sklearn 라이브러리에서 로지스틱 분류 모형 가져오기
from sklearn.linear_model import LogisticRegression

# 모형 객체 생성 (kernel='rbf' 적용)
logi_model = LogisticRegression()
logi_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
'''
[Step 6] train data를 가지고 모형 학습
'''

# train data를 가지고 모형 학습
logi_model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
'''
[Step 7] test data를 가지고 y_hat을 예측 (분류) 
'''

# test data를 가지고 y_hat을 예측 (분류) 
y_hat = logi_model.predict(X_test)

print(y_hat[0:10])
print(y_test.values[0:10])
print('\n')

[0 0 1 0 1 0 1 1 1 0]
[0 0 1 0 0 1 1 1 0 0]




In [49]:
'''
[Step 8] 모형 성능 평가 - Confusion Matrix 계산
'''

# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics 
svm_matrix = metrics.confusion_matrix(y_test, y_hat)  
print(svm_matrix)
print('\n')

# 모형 성능 평가 - 평가지표 계산
svm_report = metrics.classification_report(y_test, y_hat)            
print(svm_report)  # 정확도(accuracy) : 0.81

[[109  16]
 [ 25  65]]


              precision    recall  f1-score   support

           0       0.81      0.87      0.84       125
           1       0.80      0.72      0.76        90

    accuracy                           0.81       215
   macro avg       0.81      0.80      0.80       215
weighted avg       0.81      0.81      0.81       215



**■ 데이터 표준화**

실무에서 접하는 데이터셋은 다양한 사람들의 손에 거쳐서 만들어진다.  
여러곳에 수집한 자료들은 대소문자 구분, 약칭 활용 등 여러가지 원인에 의해서 다양한 형태로 표현된다.  
잘 정리된 것으로 보이는 자료를 자세히 들여다보면 서로 다른 단위가 섞여있거나 같은 대상을 다른 형식으로 표현하는 경우가  
의외로 많다.
그래서 단위환산을 통해서 같은 단위 형식으로 변환을 해줄 필요가 있다.  

예: 모전자에서 모제품의 판매대수를 미리 예측하여 생산라인에 다음달에 몇대가 판매가 될거라는 것을 예측해야하는 머신러닝 모델을 만들어야 하는 경우에 전세계에서 엑셀파일을 보내오는데 나라마다 단위형식이 다르다. (화폐단위, 연비단위, …)

**■ 머신러닝 데이터 분석을 하기 위한 단계?**

    1. 데이터 불러오기
                파생변수 추가
    2. 데이터 탐색 및 전처리   --->   결측치 처리
    3. 범주형 변수 더미변수(인코딩)로 변환 (파이썬)
    4. 데이터 정규화 또는 표준화  --->  이상치에 민감하지 않도록 단위를 일정하게 조정
    5. 훈련 데이터와 테스트 데이터 분할
    6. 머신러닝 모델 생성
    7. 훈련 데이터로 머신러닝 모델 훈련
    8. 머신러닝 모델 평가
    9. 머신러닝 모델 성능 개선

문제35. women_child 파행변수를 추가하고 다시 학습시켜서 모델의 성능을 확인하시오 !


In [50]:
### 기본 라이브러리 불러오기
import pandas as pd
import seaborn as sns

'''
[Step 1] 데이터 준비/ 기본 설정
'''

# load_dataset 함수를 사용하여 데이터프레임으로 변환
df = sns.load_dataset('titanic')

#  IPython 디스플레이 설정 - 출력할 열의 개수 한도 늘리기
pd.set_option('display.max_columns', 15)
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [51]:
# 여자와 아이에 대한 파생변수 추가
mask = ( df.age < 10 ) | ( df.sex=='female')
mask.astype(int) # True 를 1 로 변경하고 False 를 0 으로 변경
df['women_child'] = mask.astype(int)
df

survived  pclass     sex   age  sibsp  parch     fare  ...    who  \
0           0       3    male  22.0      1      0   7.2500  ...    man   
1           1       1  female  38.0      1      0  71.2833  ...  woman   
2           1       3  female  26.0      0      0   7.9250  ...  woman   
3           1       1  female  35.0      1      0  53.1000  ...  woman   
4           0       3    male  35.0      0      0   8.0500  ...    man   
..        ...     ...     ...   ...    ...    ...      ...  ...    ...   
886         0       2    male  27.0      0      0  13.0000  ...    man   
887         1       1  female  19.0      0      0  30.0000  ...  woman   
888         0       3  female   NaN      1      2  23.4500  ...  woman   
889         1       1    male  26.0      0      0  30.0000  ...    man   
890         0       3    male  32.0      0      0   7.7500  ...    man   

    adult_male deck  embark_town alive  alone women_child  
0         True  NaN  Southampton    no  False           0  
1        False    C    Cherbourg   yes  False           1  
2        False  NaN  Southampton   yes   True           1  
3        False    C  Southampton   yes  False           1  
4         True  NaN  Southampton    no   True           0  
..         ...  ...          ...   ...    ...         ...  
886       True  NaN  Southampton    no   True           0  
887      False    B  Southampton   yes   True           1  
888      False  NaN  Southampton    no  False           1  
889       True    C    Cherbourg   yes   True           0  
890       True  NaN   Queenstown    no   True           0  

[891 rows x 16 columns]

In [53]:
# ### 결측치 확인
print(df.isnull().sum())
print('\n')
print(df.info())
print('\n')

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
women_child      0
dtype: int64


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck        

In [55]:
'''
[Step 2] 데이터 탐색/ 전처리
'''

# NaN값이 많은 deck 열을 삭제, embarked와 내용이 겹치는 embark_town 열을 삭제
rdf = df.drop(['deck', 'embark_town'], axis=1)  

# age 열에 나이 데이터가 없는 모든 행을 삭제 - age 열(891개 중 177개의 NaN 값)
rdf = rdf.dropna(subset=['age'], how='any', axis=0)  

# embarked 열의 NaN값을 승선도시 중에서 가장 많이 출현한 값으로 치환하기
most_freq = rdf['embarked'].value_counts(dropna=True).idxmax()   
rdf['embarked'].fillna(most_freq, inplace=True)

rdf.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
alive          0
alone          0
women_child    0
dtype: int64

In [57]:
'''
[Step 3] 분석에 사용할 속성을 선택
'''

# 분석에 활용할 열(속성)을 선택 
ndf = rdf[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked', 'women_child']]
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked  women_child
0         0       3    male  22.0      1      0        S            0
1         1       1  female  38.0      1      0        C            1
2         1       3  female  26.0      0      0        S            1
3         1       1  female  35.0      1      0        S            1
4         0       3    male  35.0      0      0        S            0

In [59]:
# 원핫인코딩 - 범주형 데이터를 모형이 인식할 수 있도록 숫자형으로 변환
onehot_sex = pd.get_dummies(ndf['sex'])
ndf = pd.concat([ndf, onehot_sex], axis=1)

onehot_embarked = pd.get_dummies(ndf['embarked'], prefix='town')
ndf = pd.concat([ndf, onehot_embarked], axis=1)

# sex, embarked 열 삭제
ndf.drop(['sex', 'embarked'], axis=1, inplace=True)

ndf

survived  pclass   age  sibsp  parch  women_child  female  male  town_C  \
0           0       3  22.0      1      0            0       0     1       0   
1           1       1  38.0      1      0            1       1     0       1   
2           1       3  26.0      0      0            1       1     0       0   
3           1       1  35.0      1      0            1       1     0       0   
4           0       3  35.0      0      0            0       0     1       0   
..        ...     ...   ...    ...    ...          ...     ...   ...     ...   
885         0       3  39.0      0      5            1       1     0       0   
886         0       2  27.0      0      0            0       0     1       0   
887         1       1  19.0      0      0            1       1     0       0   
889         1       1  26.0      0      0            0       0     1       1   
890         0       3  32.0      0      0            0       0     1       0   

     town_Q  town_S  
0         0       1  
1         0       0  
2         0       1  
3         0       1  
4         0       1  
..      ...     ...  
885       1       0  
886       0       1  
887       0       1  
889       0       0  
890       1       0  

[714 rows x 11 columns]

In [60]:
'''
[Step 4] 데이터셋 구분 - 훈련용(train data)/ 검증용(test data)
'''

# 속성(변수) 선택
X=ndf[['pclass', 'age', 'sibsp', 'parch', 'women_child', 'female', 'male', 
       'town_C', 'town_Q', 'town_S']]  #독립 변수 X
y=ndf['survived']                      #종속 변수 Y

X.head()

pclass   age  sibsp  parch  women_child  female  male  town_C  town_Q  \
0       3  22.0      1      0            0       0     1       0       0   
1       1  38.0      1      0            1       1     0       1       0   
2       3  26.0      0      0            1       1     0       0       0   
3       1  35.0      1      0            1       1     0       0       0   
4       3  35.0      0      0            0       0     1       0       0   

   town_S  
0       1  
1       0  
2       1  
3       1  
4       1

In [61]:
# 설명 변수 데이터를 정규화(normalization)
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X

array([[ 0.91123237, -0.53037664,  0.52457013, ..., -0.47180795,
        -0.20203051,  0.53307848],
       [-1.47636364,  0.57183099,  0.52457013, ...,  2.11950647,
        -0.20203051, -1.87589641],
       [ 0.91123237, -0.25482473, -0.55170307, ..., -0.47180795,
        -0.20203051,  0.53307848],
       ...,
       [-1.47636364, -0.73704057, -0.55170307, ..., -0.47180795,
        -0.20203051,  0.53307848],
       [-1.47636364, -0.25482473, -0.55170307, ...,  2.11950647,
        -0.20203051, -1.87589641],
       [ 0.91123237,  0.15850313, -0.55170307, ..., -0.47180795,
         4.94974747, -1.87589641]])

In [62]:
# train data 와 test data로 구분(7:3 비율)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10) 

print('train data 개수: ', X_train.shape)
print('test data 개수: ', X_test.shape)
print('\n')

train data 개수:  (499, 10)
test data 개수:  (215, 10)




In [63]:
'''
[Step 5] 로지스틱 분류 모형 - sklearn 사용
'''

# sklearn 라이브러리에서 로지스틱 분류 모형 가져오기
from sklearn.linear_model import LogisticRegression

# 모형 객체 생성 (kernel='rbf' 적용)
logi_model = LogisticRegression()
logi_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [64]:
'''
[Step 6] train data를 가지고 모형 학습
'''

# train data를 가지고 모형 학습
logi_model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [65]:
'''
[Step 7] test data를 가지고 y_hat을 예측 (분류) 
'''

# test data를 가지고 y_hat을 예측 (분류) 
y_hat = logi_model.predict(X_test)

print(y_hat[0:10])
print(y_test.values[0:10])
print('\n')

[0 0 1 0 1 1 1 1 0 0]
[0 0 1 0 0 1 1 1 0 0]




In [66]:
'''
[Step 8] 모형 성능 평가 - Confusion Matrix 계산
'''

# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics 
svm_matrix = metrics.confusion_matrix(y_test, y_hat)  
print(svm_matrix)
print('\n')

[[112  13]
 [ 19  71]]




In [67]:
# 모형 성능 평가 - 평가지표 계산
svm_report = metrics.classification_report(y_test, y_hat)            
print(svm_report)  # women_child 파생변수 추가 후 정확도(accuracy) : 0.85

              precision    recall  f1-score   support

           0       0.85      0.90      0.88       125
           1       0.85      0.79      0.82        90

    accuracy                           0.85       215
   macro avg       0.85      0.84      0.85       215
weighted avg       0.85      0.85      0.85       215



**■ 성능 개선을 위해 데이터를 시각화 해서 데이터에서 스토리를 뽑아내는 방법**

** 범주형 데이터를 처리하는 방법

    1. 더미변수로 처리 : 숫자 0과 1로 표현하는 것
    예: 여자 또는 아니는 1이고 아니면 0 으로 표현
    
    2. 구간 분할로 처리 : 일정한 구간으로 나눔
    예: 미세먼지의 농도는 연속형 수치형 데이터여서 누군가가 나에게 오늘 미세먼지 농도를
    물어봤을때 63 ㎍/㎥ 입니다 라고 하면 전문가가 아니면 알아듣기 어렵습니다.
    그냥 좋음, 보통, 나쁨, 매우나쁨 이라고 알려주는게 훨씬 이해하기 편합니다.

    예: 타이타닉 데이터도 운임 컬럼을 low, medium-low, medium, high 구간 분할 하면
    기계가 훨씬 더 잘 이해해서 성능이 더 올라가게 됩니다.


**□ 구간분할 설명을 위해 필요한 준비 스크립트**

In [75]:
import pandas as pd
import numpy as np

# CSV 파일을 데이터프레임으로 변환
df = pd.read_csv('/content/drive/MyDrive/data/auto-mpg.csv', header=None)

# 열 이름 지정
df.columns = ['mpg','cylinders','displacement','horsepower','weight',
 'acceleration','model year','origin','name']

# 데이터 살펴보기
print(df.head())
print('\n')

# IPython 디스플레이 설정 - 출력할 열의 개수 한도 늘리기
pd.set_option('display.max_columns', 10)

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  




In [76]:
'''
[Step 2] 데이터 탐색
'''
# 데이터 자료형 확인
print(df.info())
print('\n')

# 설명: horsepower 가 object(문자형) 여서 수치형 데이터로 변경해야합니다. 
# 전처리가 필요한 문자가 포함되어있어서 object 문자형으로 출력되고 있습니다. 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None




In [77]:
# 데이터 통계 요약정보 확인
print(df.describe())
print('\n')

# 설명:  horsepower 가 출력값에서 빠졌다.
# 통계요약정보를 출력하려면 숫자형 데이터여야 출력될 수 있습니다. 

# mpg 는 mile per gallon 의 약자로 영국과 미국에서는 한국과는 달리
# 갤런당 마일 단위로 연비를 표시합니다.
# 한국은 리터당 킬로미터(km/L) 단위로 표시한다.
# mpg 열을 한국에서 사용하는 km/L 로 변환해줘야 합니다. 
# 1 갤런이 3.78541 이다. 그리고 1마일이 1.60934 km 이다.
# 그렇다면 1 mpg(mile per  gallon) 은 ?

# print  ( 1.60934 /  3.78541 )  # 0.425  km/L 

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000  




In [78]:
# horsepower 열의 자료형 변경 (문자열 ->숫자)
print(df['horsepower'].unique()) # horsepower 열의 고유값 확인
print('\n')

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']




In [80]:
df['horsepower'].replace('?', np.nan, inplace=True) # '?'을 np.nan으로 변경

df.dropna(subset=['horsepower'], axis=0, inplace=True) # 누락데이터 행을 삭제

df['horsepower'] = df['horsepower'].astype('float') # 문자열을 실수형으로 변환

print(df.describe()) # 데이터 통계 요약정보 확인
print('\n')

              mpg   cylinders  displacement  horsepower       weight  \
count  392.000000  392.000000    392.000000  392.000000   392.000000   
mean    23.445918    5.471939    194.411990  104.469388  2977.584184   
std      7.805007    1.705783    104.644004   38.491160   849.402560   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2225.250000   
50%     22.750000    4.000000    151.000000   93.500000  2803.500000   
75%     29.000000    8.000000    275.750000  126.000000  3614.750000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    392.000000  392.000000  392.000000  
mean      15.541327   75.979592    1.576531  
std        2.758864    3.683737    0.805518  
min        8.000000   70.000000    1.000000  
25%       13.775000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.025000   79.0000

In [82]:
# 판다스의 cut() 함수를 이용해서 horsepower 를 구간 분할하기

count, bin_dividers = np.histogram(df.horsepower, bins=3)
print(count)   # 각 구간에 속하는 값의 개수
print('\n')
print(bin_dividers)  # 경계값 리스트 
print('\n')

# 설명: 107 - 46 = 61, 168 - 107 = 61, 230 - 169 = 61

[257 103  32]


[ 46.         107.33333333 168.66666667 230.        ]




In [84]:
bin_names = ['저출력', '보통출력', '고출력']
df['hp_bin'] = pd.cut( x = df.horsepower, bins=bin_dividers, labels=bin_names)
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0  3504.0          12.0   
1    15.0          8         350.0       165.0  3693.0          11.5   
2    18.0          8         318.0       150.0  3436.0          11.0   
3    16.0          8         304.0       150.0  3433.0          12.0   
4    17.0          8         302.0       140.0  3449.0          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0  2790.0          15.6   
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     model year  origin                       name hp_bin  
0            70       1  chevrolet chevelle malibu   보통출력  
1            70       1          buick skylark 320   보통출력  
2            70       1         plymouth satellite   보통출력  
3            70       1              amc rebel sst   보통출력  
4            70       1                ford torino   보통출력  
..          ...     ...                        ...    ...  
393          82       1            ford mustang gl    저출력  
394          82       2                  vw pickup    저출력  
395          82       1              dodge rampage    저출력  
396          82       1                ford ranger    저출력  
397          82       1                 chevy s-10    저출력  

[392 rows x 10 columns]

설명: 이처럼 연속형 변수를 일정한 구간으로 나눠 각 구간을 범주형 이산 변수로 변환하는 과정을 구간분할(binning) 이라고 합니다.  
	판다스의 cut() 함수를 이용하면 연속 데이터를 여러 구간으로 나누고 범주형 데이터로 변환할 수 있니다.

문제36. emp 데이터 프레임의 월급을 3개로 구간 분할 하는데 고소득, 중간소득, 저소득으로 나눠서 출력하는 sal_bin 이라는 파생변수를 추가하시오

In [87]:
import pandas as pd
import numpy as np

emp = pd.read_csv('/content/drive/MyDrive/data/emp.csv')

count, bin_dividers = np.histogram(emp.sal, bins=3)
print(count)   # 각 구간에 속하는 값의 개수
print('\n')
print(bin_dividers) # 경계값 리스트 
print('\n')

bin_names = ['저소득', '중간소득', '고소득']
emp['sal_bin'] = pd.cut( x = emp.sal, bins=bin_dividers, labels=bin_names, include_lowest=True) 
emp

[8 6 1]


[ 800. 2200. 3600. 5000.]




empno   ename        job     mgr    hiredate   sal    comm  deptno sal_bin
0    7369   SMITH      CLERK  7902.0  1980-12-17   800     NaN      20     저소득
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600   300.0      30     저소득
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250   500.0      30     저소득
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975     NaN      20    중간소득
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250  1400.0      30     저소득
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850     NaN      30    중간소득
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450     NaN      10    중간소득
7    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000     NaN      20    중간소득
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000     NaN      10     고소득
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500     0.0      30     저소득
10   7876   ADAMS      CLERK  7788.0  1987-05-23  1100     NaN      20     저소득
11   7900   JAMES      CLERK  7698.0  1981-12-03   950     NaN      30     저소득
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000     NaN      20    중간소득
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300     NaN      10     저소득
14   9292    JACK      CLERK  7782.0  1982-01-23  3200     NaN      70    중간소득

문제37. 여자와 아이에 대한 파생변수를 추가해서 0.85 까지 올렸던 코드를 로지스틱 회귀가 아니라 앙상블 기법이 추가된 랜덤포레스트로 수행해서 정확도가 더 올라가는지 확인하시오

In [88]:
### 기본 라이브러리 불러오기
import pandas as pd
import seaborn as sns

'''
[Step 1] 데이터 준비/ 기본 설정
'''

# load_dataset 함수를 사용하여 데이터프레임으로 변환
df = sns.load_dataset('titanic')

# 여자와 아이에 대한 파생변수 추가
mask = ( df.age < 10 ) | ( df.sex=='female')
mask.astype(int) # True 를 1 로 변경하고 False 를 0 으로 변경
df['women_child'] = mask.astype(int)
df

survived  pclass     sex   age  sibsp  ...  deck  embark_town alive  \
0           0       3    male  22.0      1  ...   NaN  Southampton    no   
1           1       1  female  38.0      1  ...     C    Cherbourg   yes   
2           1       3  female  26.0      0  ...   NaN  Southampton   yes   
3           1       1  female  35.0      1  ...     C  Southampton   yes   
4           0       3    male  35.0      0  ...   NaN  Southampton    no   
..        ...     ...     ...   ...    ...  ...   ...          ...   ...   
886         0       2    male  27.0      0  ...   NaN  Southampton    no   
887         1       1  female  19.0      0  ...     B  Southampton   yes   
888         0       3  female   NaN      1  ...   NaN  Southampton    no   
889         1       1    male  26.0      0  ...     C    Cherbourg   yes   
890         0       3    male  32.0      0  ...   NaN   Queenstown    no   

     alone women_child  
0    False           0  
1    False           1  
2     True           1  
3    False           1  
4     True           0  
..     ...         ...  
886   True           0  
887   True           1  
888  False           1  
889   True           0  
890   True           0  

[891 rows x 16 columns]

In [89]:
'''
[Step 2] 데이터 탐색/ 전처리
'''

# NaN값이 많은 deck 열을 삭제, embarked와 내용이 겹치는 embark_town 열을 삭제
rdf = df.drop(['deck', 'embark_town'], axis=1)  

# age 열에 나이 데이터가 없는 모든 행을 삭제 - age 열(891개 중 177개의 NaN 값)
rdf = rdf.dropna(subset=['age'], how='any', axis=0)  

# embarked 열의 NaN값을 승선도시 중에서 가장 많이 출현한 값으로 치환하기
most_freq = rdf['embarked'].value_counts(dropna=True).idxmax()   
rdf['embarked'].fillna(most_freq, inplace=True)

In [90]:
'''
[Step 3] 분석에 사용할 속성을 선택
'''

# 분석에 활용할 열(속성)을 선택 
ndf = rdf[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked','women_child']]
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked  women_child
0         0       3    male  22.0      1      0        S            0
1         1       1  female  38.0      1      0        C            1
2         1       3  female  26.0      0      0        S            1
3         1       1  female  35.0      1      0        S            1
4         0       3    male  35.0      0      0        S            0

In [91]:
# 원핫인코딩 - 범주형 데이터를 모형이 인식할 수 있도록 숫자형으로 변환
onehot_sex = pd.get_dummies(ndf['sex'])
ndf = pd.concat([ndf, onehot_sex], axis=1)

onehot_embarked = pd.get_dummies(ndf['embarked'], prefix='town')
ndf = pd.concat([ndf, onehot_embarked], axis=1)

ndf.drop(['sex', 'embarked'], axis=1, inplace=True)
ndf.head()

survived  pclass   age  sibsp  parch  ...  female  male  town_C  town_Q  \
0         0       3  22.0      1      0  ...       0     1       0       0   
1         1       1  38.0      1      0  ...       1     0       1       0   
2         1       3  26.0      0      0  ...       1     0       0       0   
3         1       1  35.0      1      0  ...       1     0       0       0   
4         0       3  35.0      0      0  ...       0     1       0       0   

   town_S  
0       1  
1       0  
2       1  
3       1  
4       1  

[5 rows x 11 columns]

In [92]:
'''
[Step 4] 데이터셋 구분 - 훈련용(train data)/ 검증용(test data)
'''

# 속성(변수) 선택
X=ndf[['pclass', 'age', 'sibsp', 'parch', 'female', 'male', 
       'town_C', 'town_Q', 'town_S','women_child']]  #독립 변수 X
y=ndf['survived']                      #종속 변수 Y

# 설명 변수 데이터를 정규화(normalization)
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

# train data 와 test data로 구분(7:3 비율)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10) 

print('train data 개수: ', X_train.shape)
print('test data 개수: ', X_test.shape)
print('\n')

train data 개수:  (499, 10)
test data 개수:  (215, 10)




In [93]:
'''
[Step 5] 랜덤 포레스트 분류 모형 - sklearn 사용
'''

# sklearn 라이브러리에서 랜덤포레스트 분류 모형 가져오기
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# 모형 객체 생성 (kernel='rbf' 적용)
tree_model = RandomForestClassifier( n_estimators=100,
                                                   oob_score=True,
                                                    random_state= 9 )  
tree_model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=9, verbose=0,
                       warm_start=False)

In [94]:
'''
[Step 6] train data를 가지고 모형 학습
'''

# train data를 가지고 모형 학습
tree_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=9, verbose=0,
                       warm_start=False)

In [95]:
'''
[Step 7] test data를 가지고 y_hat을 예측 (분류) 
'''

# test data를 가지고 y_hat을 예측 (분류) 
y_hat = tree_model.predict(X_test)

print(y_hat[0:10])
print(y_test.values[0:10])
print('\n')

[0 0 1 0 0 1 1 0 0 0]
[0 0 1 0 0 1 1 1 0 0]




In [96]:
'''
[Step 8] 모형 성능 평가 - Confusion Matrix 계산
'''

# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics 
svm_matrix = metrics.confusion_matrix(y_test, y_hat)  
print(svm_matrix)
print('\n')

# 모형 성능 평가 - 평가지표 계산
svm_report = metrics.classification_report(y_test, y_hat)            
print(svm_report)   # 정확도(accuracy) : 0.78

[[104  21]
 [ 26  64]]


              precision    recall  f1-score   support

           0       0.80      0.83      0.82       125
           1       0.75      0.71      0.73        90

    accuracy                           0.78       215
   macro avg       0.78      0.77      0.77       215
weighted avg       0.78      0.78      0.78       215



문제38. 로지스틱 회귀로 시본의 타이타닉 분류 모델을 만드는데
	    여자와 아이 파생변수 말고 아래의 그래프를 보고 더 좋은 파생변수를 생각해서 학습시키고 정확도 출력하시오
